### ISSUE TITLE
parts 

### ISSUE THREAD

**Issue by xblox** [xblox/claycenter#1]
1. triggered playback of wav files
2. meters
3. testing 24fps clock display
4. pop up window with list menu
5. everything else basic buttons/drivers
6. then export and test for several days for reliability

**Comment by gbaumgart** [comment]
would be great to you explain 1/2/3/4

**Comment by MediaMerge** [comment]
I'll use this to help keep a list of things I need your assistance on to resolve for this project.

let's start with #4:

There are buttons where the operator can press to get a menu of available shows (previously created on media server). In previous version the sequence went like this:

1. user press button (for example) "feature"
2. we send a udp command to the media server for playlists and the playlist paths
3. media server responds with both which I put in a array "playlist[x,1], playlist path[x,2]
3. I then load menu of playlist into windows modal list pop up window
4. user selects playlist they want to load, hits ok, window closes, playlist name then shows in text window, and the corresponding row position in array loaded into variable which will be used to call playlist when user finally presses play

I think I can get 1 & 2 happening. Need widget for modal pop up window that can be called from driver...

**Comment by gbaumgart** [comment]
well, 
1) i started a driver to trigger things on the custom MPD setup I've sent your a few weeks ago, still need some work there

2) not so sure

4) 
- there is currently only dropdown widget but no popup
- how is that playlist on that media-server? is that something different from the Music server I created (MPD)? and if so, I guess you're creating a driver for this as well!?
- however, i can only think of some custom Javascript which feeds the dropdown/popup with items. doing this with visual tools being created first could last 1-2 weeks.

**Comment by gbaumgart** [comment]
i guess i have to mention that currently there is no real convenient or visual way to access driver data from within VE scenes.

**Comment by MediaMerge** [comment]
1) they are announcement files. The user selects an announcement then presses play. This would be seperate from music player and must be on different sound card channels.
2) basically we receive numeric values that will need to convert to an audio meter level ad shown at top of layout
4) drop down may work but text must be large enough to select via touch.

Yes, there is a driver. Simple query over UDP

Modal Popup window very common need.

**Comment by gbaumgart** [comment]
1) ok, i guess, more actual details come later.
2) ok, just hope it won't ruin the whole app by massive data coming in
4) ok

modal popup is no problem, just that you need to do that with a few lines js

**Comment by gbaumgart** [comment]
2) we could create a fake FFT if really needed. this what the most web mp3 player do btw.
